---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: azure-config
  namespace: flux-system
  annotations:
    metadata.weave.works/description: This is a sample set of objects for Azure such as role bindings for US East.
spec:
  interval: 10m
  approvePlan: auto
  path: ./base/terraform/azure-config
  sourceRef:
    kind: GitRepository
    name: flux-system
  runnerPodTemplate:
    spec:
      envFrom:
      - secretRef:
          name: azure-tf-credentials
  enableInventory: true
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: azure-functions
  namespace: flux-system
  annotations:
    metadata.weave.works/description: This is a sample set of objects for Azure functions.
spec:
  interval: 10m
  approvePlan: auto
  path: ./base/terraform/azure-functions
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: azure-web-pubsub
  runnerPodTemplate:
    spec:
      envFrom:
      - secretRef:
          name: azure-tf-credentials
  enableInventory: true
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: azure-web-pubsub
  namespace: flux-system
  annotations:
    metadata.weave.works/description: This is a sample set of objects for Azure Web PubSub.
spec:
  interval: 2m
  approvePlan: auto
  path: ./base/terraform/azure-web-pubsub
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: azure-config
  runnerPodTemplate:
    spec:
      envFrom:
      - secretRef:
          name: azure-tf-credentials
  enableInventory: true
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: azure-mobile-api-pubsub
  namespace: flux-system
  annotations:
    metadata.weave.works/description: This is a sample set of objects for Azure Web PubSub.
spec:
  interval: 2m
  approvePlan: auto
  path: ./base/terraform/azure-mobile-pubsub
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: azure-config
  runnerPodTemplate:
    spec:
      envFrom:
      - secretRef:
          name: azure-tf-credentials
  enableInventory: true